[package]
name = "virtio-blk"
description = "Driver for virtio block devices (disks)"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "virtio-blk"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
