[package]
name = "vui"
description = "The Vindows GUI toolkit: windows, event loop, widgets, icons and dialogs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vrt = { workspace = true, default-features = false }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vgfx = { workspace = true }
vmath = { workspace = true }
vraster = { workspace = true }
vfiles = { workspace = true }
vjson = { workspace = true }

[lints]
workspace = true
