[package]
name = "virtio-net"
description = "Driver for virtio network cards"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "virtio-net"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
