[package]
name = "devmgr"
description = "Device manager: enumerates PCI devices, reads the firmware's ACPI tables and starts the drivers"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "devmgr"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
initrd = { workspace = true }
vacpi = { workspace = true }
vgpio = { workspace = true }
viommu = { workspace = true }
vhv = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
