[package]
name = "vboot"
description = "The Veda UEFI boot loader"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vboot"
test = false
bench = false

[dependencies]
bootinfo = { workspace = true }
vpe = { workspace = true }
vsplash = { workspace = true }

[lints]
workspace = true
