[package]
name = "terminal"
description = "Terminal with a command shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "terminal"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vgfx = { workspace = true }
vfiles = { workspace = true }
vui = { workspace = true }
vnet = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
