[package]
name = "testmic"
description = "A microphone for automated tests: audio streamed from the host over TCP"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "testmic"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vnet = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
