[package]
name = "files"
description = "Files: file manager"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "files"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vgfx = { workspace = true }
vimage = { workspace = true }
vui = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
