# The GNU Compiler Collection (C).
name = "gcc"
version = "16.2.0"
url = "https://ftp.gnu.org/gnu/gcc/gcc-16.2.0/gcc-16.2.0.tar.xz"
sha256 = "e6738e29597f733270731aa90600f37ffdc045079dfc27ec7e8192cc81085c3e"
license = "GPL-3.0-or-later WITH GCC-exception-3.1"
