[package]
name = "shell"
description = "The desktop shell: wallpaper, taskbar, start menu and notifications"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "shell"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vgfx = { workspace = true }
vmath = { workspace = true }
vimage = { workspace = true }
vfiles = { workspace = true }
vui = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
