[package]
name = "guest-alsa"
description = "Veda's sound driver for Linux: an ALSA sound card as Veda's output device"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "alsa"
path = "src/main.rs"
bench = false

[dependencies]
vrt = { workspace = true, default-features = false }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
guest-sys = { workspace = true }

[lints]
workspace = true
