[package]
name = "about"
description = "About Vindows: version and system information"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "about"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vui = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
