[package]
name = "systest"
description = "In-system integration tests for Veda (run by `cargo xtask test`)"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "systest"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vgl = { workspace = true, features = ["veda"] }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
