[package]
name = "vwifi"
description = "Driver for the virtual Wi-Fi radio (a virtio-serial port connected to airsim under QEMU)"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vwifi"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }
vradiolink = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
