[package]
name = "virtio-gpu"
description = "Driver for virtio-gpu devices with 3D support: per-client virgl contexts on the host's GPU"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "virtio-gpu"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
