[package]
name = "vkernel"
description = "The Veda microkernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vkernel"
test = false
bench = false

[dependencies]
bootinfo = { workspace = true }
vabi = { workspace = true }
vpe = { workspace = true }
initrd = { workspace = true }
ventropy = { workspace = true }
vhv = { workspace = true }
viommu = { workspace = true }

[lints]
workspace = true
