[package]
name = "guest-input"
description = "Veda's input driver for Linux: Linux's keyboards, mice, tablets and touchscreens as Veda's input devices"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "input"
path = "src/main.rs"
test = false
bench = false

[dependencies]
vrt = { workspace = true, default-features = false }
vproto = { workspace = true }
guest-sys = { workspace = true }

[lints]
workspace = true
