[package]
name = "virtio-input"
description = "Driver for virtio input devices (tablet, keyboard, mouse)"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "virtio-input"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
