[package]
name = "e1000"
description = "Driver for Intel PRO/1000 network cards (82540EM, 82545EM, 82574L)"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "e1000"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
