[package]
name = "starfall"
description = "Starfall: a 3D space shooter"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "starfall"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
v3d = { workspace = true, features = ["app"] }
vmath = { workspace = true }
vproto = { workspace = true }
vgfx = { workspace = true }
vui = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
