[package]
name = "vweb"
description = "Web clients for Veda applications: URLs, HTTP/1.1 and WebSocket over TCP or TLS"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vrt = { workspace = true, default-features = false }
vabi = { workspace = true }
vnet = { workspace = true }
vtls = { workspace = true }
httparse = { workspace = true }
sha1 = { workspace = true }

[lints]
workspace = true
