[package]
name = "vgfx"
description = "Veda 2D graphics: blending, shapes, shadows, images and text on pixel surfaces"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vmath = { workspace = true }
vraster = { workspace = true }
vfont = { workspace = true }

[lints]
workspace = true
