[package]
name = "ac97"
description = "Driver for AC'97 sound controllers (VirtualBox's ICH AC97, QEMU's AC97): playback and the microphone"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ac97"
test = false
bench = false

[dependencies]
vrt = { workspace = true }
vabi = { workspace = true }
vipc = { workspace = true }
vproto = { workspace = true }
vvirtio = { workspace = true }

[build-dependencies]
vbuild = { workspace = true }

[lints]
workspace = true
